# Generated by Django 5.1.6 on 2025-11-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_name', models.TextField()),
                ('requester_club', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('pending', 'Đang chờ xử lý'), ('accepted', 'Đã lên kèo'), ('rejected', 'Bị từ chối')], default='pending', max_length=20)),
                ('start_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
