# Generated by Django 5.1.6 on 2025-11-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchrequest',
            name='start_date',
            field=models.TextField(),
        ),
    ]
